version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  assignees:
  - samhamilton
  commit-message:
    prefix: "chore(bot):"
  groups:
    actions:
      patterns: ["*"]
    actions-security:
      applies-to: "security-updates"
      patterns: ["*"]

- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: "monthly"
  assignees:
  - samhamilton
  commit-message:
    prefix: "chore(bot):"
  groups:
    elixir:
      patterns: ["*"]
      update-types: ["minor", "patch"]
