name: Elixir
on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MIX_ENV: test

# https://github.com/elixir-lang/elixir/blob/main/lib/elixir/pages/references/compatibility-and-deprecations.md
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27.x"
          elixir-version: "1.18.x"
      - uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix deps.unlock --check-unused
      - run: mix hex.audit
      # -run: mix doctor
      - run: mix format --dry-run --check-formatted
      - run: mix sobelow --config
      - run: mix format --dry-run --check-formatted
      - run: mix credo --strict
      - run: mix dialyzer
      - run: elixir --logger-sasl-reports true -S mix coveralls.json
      - uses: codecov/codecov-action@v5

  elixir_1_18:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [25.x, 26.x, 27.x]
        elixir: [1.18.x]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix do deps.get, compile --all-warnings --warnings-as-errors
      - run: mix test

  elixir_1_17:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [25.x, 26.x, 27.x]
        elixir: [1.17.x]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix do deps.get, compile --all-warnings --warnings-as-errors
      - run: mix test

  elixir_1_16:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [24.x, 25.x, 26.x]
        elixir: [1.16.x]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix do deps.get, compile --all-warnings --warnings-as-errors
      - run: mix test

  elixir_1_15:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [24.x, 25.x, 26.x]
        elixir: [1.15.x]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix do deps.get, compile --all-warnings --warnings-as-errors
      - run: mix test

  elixir_1_14:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: [24.x, 25.x]
        elixir: [1.14.x]
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix do deps.get, compile --all-warnings --warnings-as-errors
      - run: mix test
